<?php
session_start();
if($_SESSION['logeado']!="SI"){
    header("Location:/proyecto/login.php");
    session_destroy();
}
else{
    header("Location:/proyecto/login.php");
    session_destroy();
}
?>